-- Test 2 schema: the flow_006_raw table from the brief, verbatim.
-- (The doc's trailing 'GO' is SQL-Server batch syntax; dropped for Postgres.)
-- gen_random_uuid() and now() are built into Postgres 13+, so no extension needed.
CREATE SCHEMA IF NOT EXISTS pipeline;
DROP TABLE IF EXISTS pipeline.flow_006_raw CASCADE;

CREATE TABLE pipeline.flow_006_raw (
    flow_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    date_cycle_id bigint NULL,
    nomination_id varchar(36) NULL,
    metadata_id varchar(30) NULL,
    tsp varchar(15) NULL,
    tsp_short char(3) NULL,
    tsp_name varchar(100) NULL,
    cycle_id smallint NULL,
    hourly_cycle_id integer NULL,
    cycle_num smallint NULL,
    cycle_desc varchar(30) NULL,
    eff_gas_day date NULL,
    eff_gas_day_time varchar(15) NULL,
    end_eff_gas_day date NULL,
    end_eff_gas_day_time varchar(15) NULL,
    post_date date NULL,
    post_time varchar(25) NULL,
    cap_type_desc varchar(75) NULL,
    loc varchar(15) NULL,
    loc_prop varchar(15) NULL,
    loc_name varchar(150) NULL,
    loc_segment varchar(25) NULL,
    loc_zone varchar(25) NULL,
    flow_id smallint NULL,
    flow_short varchar(25) NULL,
    loc_purp_desc varchar(50) NULL,
    loc_qti_id smallint NULL,
    loc_qti_short char(3) NULL,
    loc_qti varchar(10) NULL,
    loc_qti_desc varchar(75) NULL,
    meas_basis_desc varchar(75) NULL,
    it_id smallint NULL,
    it_num smallint NULL,
    it_desc varchar(75) NULL,
    design_capacity double precision NULL,
    operating_capacity double precision NULL,
    scheduled_quantity double precision NULL,
    operationally_available double precision NULL,
    unsubscribed_capacity double precision NULL,
    no_notice_quantity double precision NULL,
    storage_capacity double precision NULL,
    storage_quantity double precision NULL,
    storage_pct_full numeric(3,2) NULL,
    design_description varchar(25) NULL,
    bidirectional varchar(25) NULL,
    source_type_id integer NULL,
    scrape_date timestamp NULL,
    loc_key varchar(20) NULL,
    file_name varchar(255) NULL,
    tsq_sign smallint NULL,
    load_date timestamp NULL DEFAULT now(),
    CONSTRAINT pk_flow_006_raw PRIMARY KEY(flow_uuid)
);
